// All GCC shipping services by country with descriptions
export const gccShippingServices = {
  AE: [
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة رائدة في خدمات الشحن السريع والحلول اللوجستية في المنطقة' },
    { id: 'dhl', name: 'دي إتش إل - DHL', key: 'dhl', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'empost', name: 'البريد الإماراتي - Emirates Post', key: 'empost', description: 'المشغل الوطني للبريد في دولة الإمارات العربية المتحدة' },
    { id: 'albaraka', name: 'البركة للتجارة والشحن - Al Baraka', key: 'albaraka', description: 'مجموعة البركة للتجارة والشحن - خدمات شحن وبنكية متكاملة' },
    { id: 'alfuttaim', name: 'الفطيم للتجارة والشحن - Al Futtaim', key: 'alfuttaim', description: 'مجموعة الفطيم للتجارة والشحن - حلول لوجستية متكاملة' },
    { id: 'alshaya', name: 'الشايع للتجارة والشحن - Al Shaya', key: 'alshaya', description: 'مجموعة الشايع التجارية - خدمات شحن وتوزيع' },
    { id: 'shipco', name: 'شركة الشحن العالمية - ShipCo', key: 'shipco', description: 'شركة الشحن العالمية - خدمات شحن دولي ومحلي' },
  ],
  SA: [
    { id: 'smsa', name: 'سمسا - SMSA', key: 'smsa', description: 'أكبر شركة شحن سعودية متخصصة في التوصيل السريع والخدمات اللوجستية' },
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة رائدة في خدمات الشحن السريع والحلول اللوجستية في المنطقة' },
    { id: 'dhl', name: 'دي إتش إل - DHL', key: 'dhl', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'zajil', name: 'زاجل - Zajil', key: 'zajil', description: 'شركة سعودية رائدة في خدمات البريد السريع والشحن' },
    { id: 'naqel', name: 'ناقل - Naqel', key: 'naqel', description: 'حلول شحن متطورة وخدمات لوجستية متكاملة داخل المملكة' },
    { id: 'saudipost', name: 'البريد السعودي - Saudi Post', key: 'saudipost', description: 'المشغل الوطني للبريد في المملكة العربية السعودية' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'alajwan', name: 'الأغوان للتجارة والشحن - Al Ajwan', key: 'alajwan', description: 'شركة الأغوان للتجارة والشحن - خدمات شحن متطورة' },
    { id: 'national', name: 'الشركة الوطنية للشحن - National Shipping', key: 'national', description: 'الشركة الوطنية للشحن - خدمات شحن وخدمات لوجستية شاملة' },
    { id: 'hellmann', name: 'هايلمان العالمية - Hellmann', key: 'hellmann', description: 'هايلمان العالمية - خدمات شحن ولوجستيات دولية' },
    { id: 'dsv', name: 'دي إس في - DSV', key: 'dsv', description: 'DSV للشحن والخدمات اللوجستية - حلول شحن متطورة' },
    { id: 'agility', name: 'مجموعة الجاهلية - Agility', key: 'agility', description: 'مجموعة الجاهلية - خدمات لوجستية وشحن متطورة' },
  ],
  KW: [
    { id: 'kwpost', name: 'البريد الكويتي - Kuwait Post', key: 'kwpost', description: 'المشغل الوطني للبريد في دولة الكويت' },
    { id: 'dhlkw', name: 'دي إتش إل - DHL', key: 'dhlkw', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة رائدة في خدمات الشحن السريع والحلول اللوجستية في المنطقة' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'albaraka', name: 'البركة للشحن - Al Baraka', key: 'albaraka', description: 'مجموعة البركة للتجارة والشحن - خدمات شحن وبنكية متكاملة' },
    { id: 'shipco', name: 'شركة الشحن العالمية - ShipCo', key: 'shipco', description: 'شركة الشحن العالمية - خدمات شحن دولي ومحلي' },
    { id: 'agility', name: 'مجموعة الجاهلية - Agility', key: 'agility', description: 'مجموعة الجاهلية - خدمات لوجستية وشحن متطورة' },
  ],
  QA: [
    { id: 'qpost', name: 'البريد القطري - Qatar Post', key: 'qpost', description: 'المشغل الوطني للبريد في دولة قطر' },
    { id: 'dhlqa', name: 'دي إتش إل - DHL', key: 'dhlqa', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة رائدة في خدمات الشحن السريع والحلول اللوجستية في المنطقة' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'albaraka', name: 'البركة للشحن - Al Baraka', key: 'albaraka', description: 'مجموعة البركة للتجارة والشحن - خدمات شحن وبنكية متكاملة' },
    { id: 'alfuttaim', name: 'الفطيم للتجارة والشحن - Al Futtaim', key: 'alfuttaim', description: 'مجموعة الفطيم للتجارة والشحن - حلول لوجستية متكاملة' },
    { id: 'hellmann', name: 'هايلمان العالمية - Hellmann', key: 'hellmann', description: 'هايلمان العالمية - خدمات شحن ولوجستيات دولية' },
  ],
  OM: [
    { id: 'omanpost', name: 'البريد العُماني - Oman Post', key: 'omanpost', description: 'المشغل الوطني للبريد في سلطنة عُمان' },
    { id: 'dhlom', name: 'دي إتش إل - DHL', key: 'dhlom', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة رائدة في خدمات الشحن السريع والحلول اللوجستية في المنطقة' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'albaraka', name: 'البركة للشحن - Al Baraka', key: 'albaraka', description: 'مجموعة البركة للتجارة والشحن - خدمات شحن وبنكية متكاملة' },
    { id: 'national', name: 'الشركة الوطنية للشحن - National Shipping', key: 'national', description: 'الشركة الوطنية للشحن - خدمات شحن وخدمات لوجستية شاملة' },
    { id: 'dsv', name: 'دي إس في - DSV', key: 'dsv', description: 'DSV للشحن والخدمات اللوجستية - حلول شحن متطورة' },
    { id: 'shipco', name: 'شركة الشحن العالمية - ShipCo', key: 'shipco', description: 'شركة الشحن العالمية - خدمات شحن دولي ومحلي' },
  ],
  BH: [
    { id: 'bahpost', name: 'البريد البحريني - Bahrain Post', key: 'bahpost', description: 'المشغل الوطني للبريد في مملكة البحرين' },
    { id: 'dhlbh', name: 'دي إتش إل - DHL', key: 'dhlbh', description: 'شبكة شحن عالمية توفر خدمات التوصيل السريع الدولي والمحلي' },
    { id: 'aramex', name: 'أرامكس - Aramex', key: 'aramex', description: 'شركة رائدة في خدمات الشحن السريع والحلول اللوجستية في المنطقة' },
    { id: 'fedex', name: 'فيديكس - FedEx', key: 'fedex', description: 'خدمات شحن دولية موثوقة مع تتبع فوري للشحنات' },
    { id: 'ups', name: 'يو بي إس - UPS', key: 'ups', description: 'حلول لوجستية متكاملة وخدمات شحن سريعة حول العالم' },
    { id: 'albaraka', name: 'البركة للشحن - Al Baraka', key: 'albaraka', description: 'مجموعة البركة للتجارة والشحن - خدمات شحن وبنكية متكاملة' },
    { id: 'alshaya', name: 'الشايع للتجارة والشحن - Al Shaya', key: 'alshaya', description: 'مجموعة الشايع التجارية - خدمات شحن وتوزيع' },
    { id: 'hellmann', name: 'هايلمان العالمية - Hellmann', key: 'hellmann', description: 'هايلمان العالمية - خدمات شحن ولوجستيات دولية' },
  ],
};

export const getServicesByCountry = (countryCode: string) => {
  return gccShippingServices[countryCode as keyof typeof gccShippingServices] || [];
};
