import { Chalet } from "@/hooks/useSupabase";

export const MOCK_CHALETS: Chalet[] = [
  // ==================== السعودية - الرياض ====================
  {
    id: "chalet_sa_riyadh_001",
    name: "شاليه الواحة الذهبية",
    country_code: "SA",
    city: "الرياض",
    address: "حي النرجس، طريق الملك عبدالله",
    default_price: 800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["مسبح خاص", "مجلس خارجي", "مطبخ مجهز", "WiFi", "موقف 4 سيارات"],
    capacity: 10,
  },
  {
    id: "chalet_sa_riyadh_002",
    name: "منتجع النخيل الفاخر",
    country_code: "SA",
    city: "الرياض",
    address: "حي الياسمين، شارع التخصصي",
    default_price: 1200,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["مسبح مدفأ", "ملعب أطفال", "شواية", "ساونا", "جاكوزي"],
    capacity: 15,
  },
  {
    id: "chalet_sa_riyadh_003",
    name: "استراحة الفردوس",
    country_code: "SA",
    city: "الرياض",
    address: "حي الملقا، طريق الأمير تركي",
    default_price: 650,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["مسبح", "ملعب كرة قدم", "مطبخ", "شواية"],
    capacity: 8,
  },
  {
    id: "chalet_sa_riyadh_004",
    name: "فندق الريتز كارلتون الرياض",
    country_code: "SA",
    city: "الرياض",
    address: "المربع، شارع العليا العام",
    default_price: 2500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "سبا فاخر", "مطاعم عالمية", "صالة رياضية", "خدمة غرف 24/7"],
    capacity: 20,
  },
  {
    id: "chalet_sa_riyadh_005",
    name: "فندق فورسيزونز الرياض",
    country_code: "SA",
    city: "الرياض",
    address: "حي السفارات، طريق الملك فهد",
    default_price: 2200,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "مسبح خارجي", "مركز مؤتمرات", "مطاعم فاخرة"],
    capacity: 18,
  },

  // ==================== السعودية - جدة ====================
  {
    id: "chalet_sa_jeddah_001",
    name: "شاليه الياسمين البحري",
    country_code: "SA",
    city: "جدة",
    address: "حي الشاطئ، كورنيش جدة الشمالي",
    default_price: 1200,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["إطلالة بحرية", "مسبح خاص", "شواية", "ألعاب مائية"],
    capacity: 15,
  },
  {
    id: "chalet_sa_jeddah_002",
    name: "منتجع البحر الأحمر",
    country_code: "SA",
    city: "جدة",
    address: "كورنيش جدة، حي الروضة",
    default_price: 1500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["شاطئ خاص", "مسبح", "مطعم", "كافيه", "ألعاب أطفال"],
    capacity: 20,
  },
  {
    id: "chalet_sa_jeddah_003",
    name: "فندق روزوود جدة",
    country_code: "SA",
    city: "جدة",
    address: "كورنيش جدة، حي الزهراء",
    default_price: 2800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "إطلالة بحرية", "سبا", "مسابح متعددة", "مطاعم عالمية"],
    capacity: 25,
  },
  {
    id: "chalet_sa_jeddah_004",
    name: "فندق بارك حياة جدة",
    country_code: "SA",
    city: "جدة",
    address: "طريق الملك عبدالعزيز، حي الفيصلية",
    default_price: 2400,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "نادي صحي", "مسبح", "مطاعم متنوعة"],
    capacity: 22,
  },

  // ==================== السعودية - الدمام ====================
  {
    id: "chalet_sa_dammam_001",
    name: "شاليه الخليج",
    country_code: "SA",
    city: "الدمام",
    address: "حي الفيحاء، كورنيش الدمام",
    default_price: 900,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["إطلالة بحرية", "مسبح", "شواية", "مجلس خارجي"],
    capacity: 12,
  },
  {
    id: "chalet_sa_dammam_002",
    name: "فندق موفنبيك الخبر",
    country_code: "SA",
    city: "الخبر",
    address: "كورنيش الخبر، حي العقربية",
    default_price: 1800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["4 نجوم", "مسبح", "شاطئ خاص", "مطاعم", "نادي رياضي"],
    capacity: 18,
  },
  {
    id: "chalet_sa_dammam_003",
    name: "منتجع نصف القمر",
    country_code: "SA",
    city: "الخبر",
    address: "شاطئ نصف القمر",
    default_price: 2000,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["منتجع شاطئي", "شاليهات متعددة", "رياضات مائية", "مطاعم"],
    capacity: 30,
  },

  // ==================== السعودية - مكة المكرمة ====================
  {
    id: "chalet_sa_makkah_001",
    name: "فندق ساعة مكة الملكية",
    country_code: "SA",
    city: "مكة المكرمة",
    address: "أبراج البيت، بجوار الحرم المكي",
    default_price: 3500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "إطلالة على الحرم", "مطاعم فاخرة", "خدمة VIP"],
    capacity: 25,
  },
  {
    id: "chalet_sa_makkah_002",
    name: "فندق هيلتون مكة",
    country_code: "SA",
    city: "مكة المكرمة",
    address: "شارع إبراهيم الخليل، جبل عمر",
    default_price: 2800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "قريب من الحرم", "مطاعم", "نقل مجاني"],
    capacity: 20,
  },

  // ==================== السعودية - المدينة المنورة ====================
  {
    id: "chalet_sa_madinah_001",
    name: "فندق دار الإيمان انتركونتيننتال",
    country_code: "SA",
    city: "المدينة المنورة",
    address: "طريق الملك عبدالعزيز، وسط المدينة",
    default_price: 2500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "قريب من الحرم النبوي", "مطاعم", "خدمة نقل"],
    capacity: 22,
  },
  {
    id: "chalet_sa_madinah_002",
    name: "فندق أنوار المدينة موڤنبيك",
    country_code: "SA",
    city: "المدينة المنورة",
    address: "طريق السلام، المنطقة المركزية",
    default_price: 2200,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "إطلالة على الحرم", "مسبح داخلي", "مطاعم"],
    capacity: 20,
  },

  // ==================== السعودية - أبها ====================
  {
    id: "chalet_sa_abha_001",
    name: "شاليه الجبل الأخضر",
    country_code: "SA",
    city: "أبها",
    address: "الجبل الأخضر، وسط المدينة",
    default_price: 700,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["إطلالة جبلية", "حديقة", "شواية", "مدفأة"],
    capacity: 10,
  },
  {
    id: "chalet_sa_abha_002",
    name: "منتجع جبل السودة",
    country_code: "SA",
    city: "أبها",
    address: "جبل السودة السياحي",
    default_price: 1100,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["منتجع جبلي", "إطلالات طبيعية", "مطاعم", "تلفريك"],
    capacity: 15,
  },

  // ==================== السعودية - الطائف ====================
  {
    id: "chalet_sa_taif_001",
    name: "استراحة الورد الطائفي",
    country_code: "SA",
    city: "الطائف",
    address: "حي الشفا، طريق الهدا",
    default_price: 800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["حديقة ورود", "مسبح", "شواية", "جلسات خارجية"],
    capacity: 12,
  },
  {
    id: "chalet_sa_taif_002",
    name: "فندق إنتركونتيننتال الطائف",
    country_code: "SA",
    city: "الطائف",
    address: "طريق المطار، حي السلامة",
    default_price: 1600,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "مسبح", "سبا", "مطاعم متعددة"],
    capacity: 18,
  },

  // ==================== الإمارات - دبي ====================
  {
    id: "chalet_ae_dubai_001",
    name: "فيلا النخيل الإماراتي",
    country_code: "AE",
    city: "دبي",
    address: "جزيرة النخلة جميرا",
    default_price: 3000,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["شاطئ خاص", "مسبح لا نهائي", "جاكوزي", "خدمة كونسيرج"],
    capacity: 20,
  },
  {
    id: "chalet_ae_dubai_002",
    name: "فندق برج العرب",
    country_code: "AE",
    city: "دبي",
    address: "جميرا، شارع جميرا",
    default_price: 8000,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["7 نجوم", "مطاعم فاخرة", "شاطئ خاص", "هليكوبتر", "سيارات رولز رويس"],
    capacity: 30,
  },
  {
    id: "chalet_ae_dubai_003",
    name: "فندق أتلانتس النخلة",
    country_code: "AE",
    city: "دبي",
    address: "جزيرة النخلة",
    default_price: 5000,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "مدينة مائية", "أكواريوم", "مطاعم عالمية", "شاطئ خاص"],
    capacity: 25,
  },
  {
    id: "chalet_ae_dubai_004",
    name: "فندق أرماني دبي",
    country_code: "AE",
    city: "دبي",
    address: "برج خليفة، وسط مدينة دبي",
    default_price: 4500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "تصميم أرماني", "سبا فاخر", "مطاعم إيطالية"],
    capacity: 22,
  },
  {
    id: "chalet_ae_dubai_005",
    name: "منتجع المها الصحراوي",
    country_code: "AE",
    city: "دبي",
    address: "محمية دبي الصحراوية",
    default_price: 3500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["منتجع صحراوي", "سفاري", "سبا", "مطعم فاخر", "مسبح خاص"],
    capacity: 15,
  },

  // ==================== الإمارات - أبوظبي ====================
  {
    id: "chalet_ae_abudhabi_001",
    name: "فندق قصر الإمارات",
    country_code: "AE",
    city: "أبوظبي",
    address: "شارع الكورنيش الغربي",
    default_price: 6000,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["7 نجوم", "شاطئ خاص", "سبا فاخر", "مطاعم عالمية", "مارينا خاصة"],
    capacity: 35,
  },
  {
    id: "chalet_ae_abudhabi_002",
    name: "فندق ياس فايسروي",
    country_code: "AE",
    city: "أبوظبي",
    address: "جزيرة ياس",
    default_price: 2800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "مطل على حلبة F1", "مسبح مع إطلالة", "مطاعم"],
    capacity: 20,
  },
  {
    id: "chalet_ae_abudhabi_003",
    name: "فندق سانت ريجيس جزيرة السعديات",
    country_code: "AE",
    city: "أبوظبي",
    address: "جزيرة السعديات",
    default_price: 3200,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "شاطئ خاص", "نادي جولف", "سبا", "مطاعم فاخرة"],
    capacity: 24,
  },
  {
    id: "chalet_ae_abudhabi_004",
    name: "منتجع الرمال الذهبية",
    country_code: "AE",
    city: "أبوظبي",
    address: "شاطئ الراحة",
    default_price: 2500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["شاطئ خاص", "مسبح", "مطاعم", "رياضات مائية"],
    capacity: 18,
  },

  // ==================== الإمارات - الشارقة ====================
  {
    id: "chalet_ae_sharjah_001",
    name: "فندق شيراتون الشارقة",
    country_code: "AE",
    city: "الشارقة",
    address: "شارع الكورنيش، خالد لاجون",
    default_price: 1200,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "إطلالة على البحيرة", "مسبح", "مطاعم"],
    capacity: 16,
  },
  {
    id: "chalet_ae_sharjah_002",
    name: "منتجع الجزيرة",
    country_code: "AE",
    city: "الشارقة",
    address: "جزيرة المنتزه",
    default_price: 1800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["منتجع عائلي", "شاطئ", "ملاهي", "مطاعم", "ألعاب أطفال"],
    capacity: 20,
  },

  // ==================== الإمارات - رأس الخيمة ====================
  {
    id: "chalet_ae_rak_001",
    name: "فندق والدورف أستوريا رأس الخيمة",
    country_code: "AE",
    city: "رأس الخيمة",
    address: "جبل جيس",
    default_price: 2500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "إطلالة جبلية", "سبا", "مطاعم فاخرة", "مسبح لا نهائي"],
    capacity: 18,
  },
  {
    id: "chalet_ae_rak_002",
    name: "منتجع الحمرا بيتش",
    country_code: "AE",
    city: "رأس الخيمة",
    address: "قرية الحمرا",
    default_price: 1600,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["شاطئ خاص", "نادي جولف", "مسبح", "مطاعم"],
    capacity: 15,
  },

  // ==================== الكويت ====================
  {
    id: "chalet_kw_kuwait_001",
    name: "شاليه الخليج الكويتي",
    country_code: "KW",
    city: "مدينة الكويت",
    address: "منطقة السالمية، شارع الخليج",
    default_price: 900,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["مسبح مدفأ", "مجلس تراثي", "مطبخ مجهز", "موقف سيارات"],
    capacity: 10,
  },
  {
    id: "chalet_kw_kuwait_002",
    name: "فندق جي دبليو ماريوت الكويت",
    country_code: "KW",
    city: "مدينة الكويت",
    address: "شارع الخليج العربي",
    default_price: 2200,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "مسبح", "سبا", "مطاعم متعددة", "قاعات احتفالات"],
    capacity: 20,
  },
  {
    id: "chalet_kw_kuwait_003",
    name: "فندق الشيراتون الكويت",
    country_code: "KW",
    city: "مدينة الكويت",
    address: "شارع فهد السالم",
    default_price: 1800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "مسبح", "نادي صحي", "مطاعم عالمية"],
    capacity: 18,
  },
  {
    id: "chalet_kw_kuwait_004",
    name: "منتجع الخيران",
    country_code: "KW",
    city: "الخيران",
    address: "منطقة الخيران السياحية",
    default_price: 1500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["منتجع ساحلي", "شاطئ", "رياضات مائية", "مطاعم"],
    capacity: 25,
  },
  {
    id: "chalet_kw_kuwait_005",
    name: "شاليه الجهراء",
    country_code: "KW",
    city: "الجهراء",
    address: "منطقة الصليبية",
    default_price: 700,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["مسبح", "حديقة", "شواية", "مجلس خارجي"],
    capacity: 12,
  },

  // ==================== قطر - الدوحة ====================
  {
    id: "chalet_qa_doha_001",
    name: "شاليه اللؤلؤة القطري",
    country_code: "QA",
    city: "الدوحة",
    address: "اللؤلؤة قطر، بورتو أرابيا",
    default_price: 1500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["إطلالة بحرية", "مسبح", "مرسى خاص", "WiFi"],
    capacity: 12,
  },
  {
    id: "chalet_qa_doha_002",
    name: "فندق الشرق",
    country_code: "QA",
    city: "الدوحة",
    address: "كتارا، المنطقة الثقافية",
    default_price: 3500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "تصميم تراثي", "شاطئ خاص", "سبا شرقي", "مطاعم فاخرة"],
    capacity: 22,
  },
  {
    id: "chalet_qa_doha_003",
    name: "فندق ماريوت ماركيز الدوحة",
    country_code: "QA",
    city: "الدوحة",
    address: "شارع الدفنة، الخليج الغربي",
    default_price: 2400,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "مسبح على السطح", "مطاعم متنوعة", "سبا"],
    capacity: 20,
  },
  {
    id: "chalet_qa_doha_004",
    name: "منتجع سيلاين بيتش",
    country_code: "QA",
    city: "مسيعيد",
    address: "شاطئ سيلاين",
    default_price: 1800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["منتجع شاطئي", "رياضات مائية", "شاليهات", "مطاعم"],
    capacity: 18,
  },
  {
    id: "chalet_qa_doha_005",
    name: "فندق سانت ريجيس الدوحة",
    country_code: "QA",
    city: "الدوحة",
    address: "الخليج الغربي، كورنيش الدوحة",
    default_price: 3000,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "شاطئ خاص", "مسبح لا نهائي", "سبا فاخر"],
    capacity: 24,
  },

  // ==================== البحرين ====================
  {
    id: "chalet_bh_manama_001",
    name: "شاليه البحرين الملكي",
    country_code: "BH",
    city: "المنامة",
    address: "منطقة السيف، شارع الفاتح",
    default_price: 850,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["مسبح", "شواية", "مجلس", "موقف سيارات"],
    capacity: 8,
  },
  {
    id: "chalet_bh_manama_002",
    name: "فندق الريتز كارلتون البحرين",
    country_code: "BH",
    city: "المنامة",
    address: "شارع الملك حمد، السيف",
    default_price: 2500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "شاطئ خاص", "سبا", "مطاعم فاخرة", "مسبح لا نهائي"],
    capacity: 20,
  },
  {
    id: "chalet_bh_manama_003",
    name: "فندق فور سيزونز خليج البحرين",
    country_code: "BH",
    city: "المنامة",
    address: "خليج البحرين",
    default_price: 2200,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "شاطئ خاص", "مسابح متعددة", "سبا", "مطاعم"],
    capacity: 18,
  },
  {
    id: "chalet_bh_manama_004",
    name: "منتجع جزر أمواج",
    country_code: "BH",
    city: "المحرق",
    address: "جزر أمواج",
    default_price: 1600,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["منتجع جزيري", "شاطئ", "مسبح", "مطاعم", "مارينا"],
    capacity: 15,
  },
  {
    id: "chalet_bh_manama_005",
    name: "فندق الخليج البحرين",
    country_code: "BH",
    city: "المنامة",
    address: "شارع القصيبية، المنامة",
    default_price: 1400,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "مسبح", "نادي صحي", "مطاعم متنوعة"],
    capacity: 16,
  },

  // ==================== عُمان - مسقط ====================
  {
    id: "chalet_om_muscat_001",
    name: "شاليه عُمان الأخضر",
    country_code: "OM",
    city: "مسقط",
    address: "منطقة القرم، شاطئ القرم",
    default_price: 700,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["حديقة خضراء", "مسبح", "مطبخ", "شواية"],
    capacity: 10,
  },
  {
    id: "chalet_om_muscat_002",
    name: "فندق شانغريلا بر الجصة",
    country_code: "OM",
    city: "مسقط",
    address: "بر الجصة، مسقط",
    default_price: 2800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "شاطئ خاص", "مسبح لا نهائي", "سبا CHI", "6 مطاعم"],
    capacity: 22,
  },
  {
    id: "chalet_om_muscat_003",
    name: "فندق الشيراتون مسقط",
    country_code: "OM",
    city: "مسقط",
    address: "منطقة روي، مطرح",
    default_price: 1600,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "إطلالة جبلية", "مسبح", "مطاعم", "نادي صحي"],
    capacity: 18,
  },
  {
    id: "chalet_om_muscat_004",
    name: "منتجع الموج مسقط",
    country_code: "OM",
    city: "مسقط",
    address: "الموج، شمال مسقط",
    default_price: 2000,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["منتجع متكامل", "نادي جولف", "شاطئ", "مارينا", "مطاعم"],
    capacity: 20,
  },
  {
    id: "chalet_om_muscat_005",
    name: "فندق إنتركونتيننتال مسقط",
    country_code: "OM",
    city: "مسقط",
    address: "شاطئ القرم",
    default_price: 1800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "شاطئ خاص", "مسبح", "سبا", "مطاعم عالمية"],
    capacity: 19,
  },

  // ==================== عُمان - صلالة ====================
  {
    id: "chalet_om_salalah_001",
    name: "منتجع صلالة الشاطئي",
    country_code: "OM",
    city: "صلالة",
    address: "شاطئ المغسيل",
    default_price: 1400,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["شاطئ خاص", "مسبح", "مطاعم", "إطلالة على المحيط"],
    capacity: 16,
  },
  {
    id: "chalet_om_salalah_002",
    name: "فندق كراون بلازا صلالة",
    country_code: "OM",
    city: "صلالة",
    address: "شاطئ صلالة السياحي",
    default_price: 1600,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "شاطئ", "مسبح", "مركز لياقة", "مطاعم"],
    capacity: 18,
  },

  // ==================== عُمان - نزوى ====================
  {
    id: "chalet_om_nizwa_001",
    name: "استراحة الجبل الأخضر",
    country_code: "OM",
    city: "نزوى",
    address: "الجبل الأخضر",
    default_price: 900,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["إطلالة جبلية", "حديقة", "شواية", "مدفأة"],
    capacity: 12,
  },
  {
    id: "chalet_om_nizwa_002",
    name: "فندق أليلا الجبل الأخضر",
    country_code: "OM",
    city: "نزوى",
    address: "الجبل الأخضر، سياج الواحة",
    default_price: 2500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["5 نجوم", "إطلالات خلابة", "مسبح لا نهائي", "سبا", "مطعم فاخر"],
    capacity: 20,
  },
];

export const getChaletsByCountry = (countryCode: string): Chalet[] => {
  return MOCK_CHALETS.filter((chalet) => chalet.country_code === countryCode);
};

export const getChaletById = (id: string): Chalet | undefined => {
  return MOCK_CHALETS.find((chalet) => chalet.id === id);
};

export const getChaletsByCity = (countryCode: string, city: string): Chalet[] => {
  return MOCK_CHALETS.filter(
    (chalet) => chalet.country_code === countryCode && chalet.city === city
  );
};

export const getAllCitiesForCountry = (countryCode: string): string[] => {
  const chalets = getChaletsByCountry(countryCode);
  const cities = [...new Set(chalets.map((chalet) => chalet.city))];
  return cities.sort();
};

export const initializeMockChalets = () => {
  if (typeof window !== 'undefined') {
    MOCK_CHALETS.forEach((chalet) => {
      const key = `local_chalets_${chalet.id}`;
      if (!localStorage.getItem(key)) {
        localStorage.setItem(key, JSON.stringify(chalet));
      }
    });
  }
};
