import { Chalet } from "@/hooks/useSupabase";

export const MOCK_CHALETS: Chalet[] = [
  {
    id: "chalet_sa_001",
    name: "منتجع وشاليهات دفلي",
    country_code: "SA",
    city: "الرياض",
    address: "حي الرمال، الرياض",
    default_price: 800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: "davliresort",
    verified: true,
    amenities: ["مسبح خارجي بعمق متدرج", "مجلس يتسع لـ20 شخص", "غرفة نوم ماستر", "ركن للشواء", "تلفزيون", "جلسات أفريقية", "2 دورة مياه", "3 مغاسل"],
    capacity: 20,
  },
  {
    id: "chalet_sa_002",
    name: "فيلا فاخرة - الواحة الذهبية",
    country_code: "SA",
    city: "الرياض",
    address: "حي النرجس، شارع التخصصي",
    default_price: 1200,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["مسبح خاص", "مجلس خارجي", "مطبخ مجهز بالكامل", "WiFi عالي السرعة", "جاكوزي", "حديقة خضراء"],
    capacity: 15,
  },
  {
    id: "chalet_sa_003",
    name: "شاليه الياسمين البحري",
    country_code: "SA",
    city: "جدة",
    address: "كورنيش جدة، حي الشاطئ",
    default_price: 1500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["إطلالة بحرية مباشرة", "مسبح مطل على البحر", "شواية خارجية", "ألعاب أطفال", "WiFi", "موقف خاص"],
    capacity: 18,
  },
  {
    id: "chalet_sa_004",
    name: "منتجع الفردوس",
    country_code: "SA",
    city: "الدمام",
    address: "حي الفيحاء، شارع الملك فهد",
    default_price: 950,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["مسبح عائلي", "ملعب أطفال", "مطبخ مجهز", "مواقف سيارات واسعة", "صالة ألعاب"],
    capacity: 12,
  },
  {
    id: "chalet_ae_001",
    name: "Bab Al Shams Desert Resort",
    country_code: "AE",
    city: "دبي",
    address: "صحراء دبي، بالقرب من الطريق الرئيسي",
    default_price: 2500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: "babalshams",
    verified: true,
    amenities: ["فيلا مع مسبح خاص", "سبا فاخر وحمام مغربي", "تجارب صحراوية فريدة", "مطاعم متعددة", "خدمة 5 نجوم", "WiFi"],
    capacity: 8,
  },
  {
    id: "chalet_ae_002",
    name: "Anantara The Palm Dubai",
    country_code: "AE",
    city: "دبي",
    address: "نخلة جميرا، دبي",
    default_price: 3500,
    images: ["/assets/hero-bg.jpg"],
    provider_id: "anantara",
    verified: true,
    amenities: ["فيلا فوق الماء", "3 مسابح بحرارة متحكمة", "شاطئ خاص", "رياضات مائية", "سبا أنانتارا", "إطلالة على الخليج العربي"],
    capacity: 6,
  },
  {
    id: "chalet_ae_003",
    name: "فيلا راقية بالمارينا",
    country_code: "AE",
    city: "دبي",
    address: "دبي مارينا",
    default_price: 2800,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["مسبح لا نهائي", "جاكوزي", "صالة رياضة خاصة", "WiFi فائق السرعة", "إطلالة على المارينا", "مطبخ حديث"],
    capacity: 10,
  },
  {
    id: "chalet_ae_004",
    name: "منتجع الإمارات الفاخر",
    country_code: "AE",
    city: "أبوظبي",
    address: "جزيرة ياس، أبوظبي",
    default_price: 3200,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["إطلالة على البحر", "مسبح أولمبي", "شاطئ خاص", "خدمة كونسيرج 24/7", "ملعب تنس", "نادي أطفال"],
    capacity: 20,
  },
  {
    id: "chalet_kw_001",
    name: "شاليه ماجيك",
    country_code: "KW",
    city: "الخيران",
    address: "صباح الأحمد البحرية، الخيران",
    default_price: 165,
    images: ["/assets/hero-bg.jpg"],
    provider_id: "magic_chalets",
    verified: true,
    amenities: ["مسبح خاص", "تكييف مركزي", "موقف سيارات", "مسموح بالحيوانات الأليفة", "إطلالة بحرية"],
    capacity: 10,
  },
  {
    id: "chalet_kw_002",
    name: "شاليه الخليج الكويتي",
    country_code: "KW",
    city: "السالمية",
    address: "منطقة السالمية، بالقرب من الشاطئ",
    default_price: 200,
    images: ["/assets/hero-bg.jpg"],
    provider_id: "mychalet",
    verified: true,
    amenities: ["مسبح مدفأ", "مجلس تراثي كويتي", "مطبخ مجهز", "موقف سيارات", "WiFi", "شواية خارجية"],
    capacity: 12,
  },
  {
    id: "chalet_kw_003",
    name: "شاليه فاخر - صباح الأحمد",
    country_code: "KW",
    city: "صباح الأحمد",
    address: "المرحلة الخامسة، الطريق 290",
    default_price: 350,
    images: ["/assets/hero-bg.jpg"],
    provider_id: "ak_shaleh",
    verified: true,
    amenities: ["9 غرف نوم (5 ماستر)", "مسبح كبير مطل على البحيرة", "مطبخ كامل", "منطقة ألعاب أطفال", "صالة كبيرة", "موقف أمامي"],
    capacity: 25,
  },
  {
    id: "chalet_qa_001",
    name: "The OQ Hotel",
    country_code: "QA",
    city: "الدوحة",
    address: "وسط مدينة الدوحة",
    default_price: 600,
    images: ["/assets/hero-bg.jpg"],
    provider_id: "the_oq",
    verified: true,
    amenities: ["مسبح خارجي", "مركز لياقة بدنية", "مطعم فاخر", "WiFi مجاني", "خدمة الغرف 24/7"],
    capacity: 4,
  },
  {
    id: "chalet_qa_002",
    name: "InterContinental Doha Beach & Spa",
    country_code: "QA",
    city: "الدوحة",
    address: "شاطئ الدوحة، منطقة الكورنيش",
    default_price: 850,
    images: ["/assets/hero-bg.jpg"],
    provider_id: "intercontinental",
    verified: true,
    amenities: ["شاطئ خاص", "سبا فاخر", "5 مطاعم", "مسابح متعددة", "نادي أطفال", "WiFi", "موقف مجاني"],
    capacity: 3,
  },
  {
    id: "chalet_qa_003",
    name: "شاليه اللؤلؤة القطري",
    country_code: "QA",
    city: "الدوحة",
    address: "اللؤلؤة قطر، بالقرب من كتارا",
    default_price: 1100,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["إطلالة بحرية بانورامية", "مسبح لا نهائي", "مرسى خاص", "WiFi", "مطبخ عصري", "جاكوزي خارجي"],
    capacity: 14,
  },
  {
    id: "chalet_bh_001",
    name: "منتجع البحرين الملكي",
    country_code: "BH",
    city: "المنامة",
    address: "منطقة السيف، بالقرب من باب البحرين",
    default_price: 400,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["مسبح كبير", "شواية خارجية", "مجلس بحريني تقليدي", "موقف سيارات", "WiFi", "حديقة خضراء"],
    capacity: 10,
  },
  {
    id: "chalet_bh_002",
    name: "فيلا البحرين الفاخرة",
    country_code: "BH",
    city: "المنامة",
    address: "منطقة عراد، قرب الشاطئ",
    default_price: 650,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["إطلالة بحرية", "مسبح خاص مدفأ", "جاكوزي", "صالة ألعاب", "مطبخ مجهز", "WiFi", "موقف خاص"],
    capacity: 12,
  },
  {
    id: "chalet_om_001",
    name: "شاليه عُمان الأخضر",
    country_code: "OM",
    city: "مسقط",
    address: "منطقة القرم، بالقرب من شاطئ القرم",
    default_price: 300,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["حديقة خضراء واسعة", "مسبح عائلي", "مطبخ تقليدي", "شواية خارجية", "WiFi", "موقف سيارات"],
    capacity: 10,
  },
  {
    id: "chalet_om_002",
    name: "منتجع الجبل الأخضر",
    country_code: "OM",
    city: "نزوى",
    address: "الجبل الأخضر، نزوى",
    default_price: 550,
    images: ["/assets/hero-bg.jpg"],
    provider_id: null,
    verified: true,
    amenities: ["إطلالة جبلية ساحرة", "مسبح طبيعي", "تراس خارجي", "مطبخ عماني تقليدي", "مدفأة", "رحلات جبلية منظمة"],
    capacity: 8,
  },
];

export const getChaletsByCountry = (countryCode: string): Chalet[] => {
  return MOCK_CHALETS.filter((chalet) => chalet.country_code === countryCode);
};

export const getChaletById = (id: string): Chalet | undefined => {
  return MOCK_CHALETS.find((chalet) => chalet.id === id);
};

export const initializeMockChalets = () => {
  if (typeof window !== 'undefined') {
    MOCK_CHALETS.forEach((chalet) => {
      const key = `local_chalets_${chalet.id}`;
      if (!localStorage.getItem(key)) {
        localStorage.setItem(key, JSON.stringify(chalet));
      }
    });
  }
};
